export const dataInfoExperto = {
  estado: "OK",
  datos: {
    rodados: false,
    telefonos: false,
    afectaciones: [],
    personasRelacionadasEmpresas: false,
    dominios: false,
    prestadoresCnc: false,
    boletinesCaba: false,
    personasRelacionadasSocios: false,
    boletinesBuenosAires: false,
    identidad: {
      cuit: "27427814799",
      numero_documento: "42781479",
      tipo_documento: "",
      nombre_completo: "PALOPOLI SASHA AYLEN",
      sexo: "F",
      fecha_nacimiento: "11/08/2000",
      clase: "2000",
      localidad: "CIUDAD AUTONOMA DE BUENOS AIRES",
      provincia: "CIUDAD AUTONOMA DE BUENOS AIRES",
      tipo_entidad: "F",
      fecha_inscripcion: "29/04/2016",
      fecha_fallecimiento: "",
      fallecido: "NO",
      cuit_baja: "NO",
      codigo_actividad: "",
      actividad: "",
      anios: "22",
      anios_inscripcion: "7",
      jubilado: "NO",
      pensionado: "NO",
      localidad_array: ["CIUDAD AUTONOMA DE BUENOS AIRES"],
      provincia_array: ["CIUDAD AUTONOMA DE BUENOS AIRES"],
    },
    personasRelacionadasRelacionRodados: false,
    boletinesCordoba: false,
    personasRelacionadasRelacionDependencia: [
      {
        cuit: "30709492922",
        nombre: "CAT TECHNOLOGIES ARGENTINA SOCIEDAD ANONIMA",
        relacion: "EMPLEADO",
      },
      { cuit: "30708291265", nombre: "GIV SRL", relacion: "EMPLEADO" },
    ],
    embargos: false,
    art: false,
    quiebraConcurso: false,
    mails: [{ mail: "P.SASHAAYLEN@GMAIL.COM" }],
    laboral: [
      {
        cuit: "30709492922",
        nombre: "CAT TECHNOLOGIES ARGENTINA SOCIEDAD ANONIMA",
        direccion:
          "PERON JUAN TTE.GRAL. 867 - CIUDAD AUTONOMA BUENOS AIRES CP:1038",
        fecha_desde: 202302,
        fecha_hasta: 202304,
      },
      {
        cuit: "30708291265",
        nombre: "GIV SRL",
        direccion:
          "GARAY JUAN DE AV. 168 12 - CIUDAD AUTONOMA BUENOS AIRES CP:1063",
        fecha_desde: 202103,
        fecha_hasta: 202104,
      },
    ],
    telefonosDeclarados: [{ numero: "1127036192" }],
    condicionTributaria: false,
    personasRelacionadas: [
      {
        cuit: "20236019994",
        nombre_completo: "PALOPOLI ALBERTO JAVIER",
        clase: "1974",
        anios: "49",
      },
      {
        cuit: "20238824274",
        nombre_completo: "DUARTE JORGE DANIEL",
        clase: "1974",
        anios: "49",
      },
      {
        cuit: "20288668117",
        nombre_completo: "FORQUEDA RODOLFO ESTEBAN",
        clase: "1981",
        anios: "42",
      },
      {
        cuit: "20365940267",
        nombre_completo: "PALOPOLI NAHUEL DARIO",
        clase: "1991",
        anios: "31",
      },
      {
        cuit: "20410052688",
        nombre_completo: "DUARTE JULIAN LUCAS DANIEL",
        clase: "1998",
        anios: "25",
      },
      {
        cuit: "20458685089",
        nombre_completo: "PALOPOLI JAVIER LUCA VALENTIN",
        clase: "2004",
        anios: "19",
      },
      {
        cuit: "20483884312",
        nombre_completo: "PALOPOLI FLORIANI AXEL DEMIAN",
        clase: "2007",
        anios: "15",
      },
      {
        cuit: "20536732706",
        nombre_completo: "PALOPOLI MARTINEZ MARTIN ARIEL",
        clase: "2013",
        anios: "9",
      },
      {
        cuit: "20547425503",
        nombre_completo: "PALOPOLI GASPAR",
        clase: "2015",
        anios: "8",
      },
      {
        cuit: "23408528259",
        nombre_completo: "GUZMAN NICOLAS ALEJANDRO",
        clase: "1997",
        anios: "25",
      },
      {
        cuit: "23562837744",
        nombre_completo: "GUZMAN UMMA LUCIA",
        clase: "2017",
        anios: "6",
      },
      {
        cuit: "27255309337",
        nombre_completo: "FLORIANI ALEJANDRA ETHEL",
        clase: "1976",
        anios: "46",
      },
      {
        cuit: "27445229348",
        nombre_completo: "PALOPOLI NATASHA MARISA",
        clase: "2002",
        anios: "20",
      },
      {
        cuit: "27550727825",
        nombre_completo: "FORQUEDA FLORIANI LOURDES FRANCESCA",
        clase: "2015",
        anios: "7",
      },
    ],
    condicionTributariaHistorial: false,
    cheques: false,
    bcra: {
      datos: [
        {
          nombre: "MERCADOLIBRE S.R.L.",
          codigo_entidad: "55311",
          deudas: [
            { periodo: "04/2023", situacion: "1", monto: "12000.00" },
            { periodo: "03/2023", situacion: "1", monto: "12000.00" },
            { periodo: "02/2023", situacion: "1", monto: "6000.00" },
            { periodo: "01/2023", situacion: "2", monto: "17000.00" },
            { periodo: "12/2022", situacion: "1", monto: "13000.00" },
            { periodo: "11/2022", situacion: "1", monto: "12000.00" },
            { periodo: "10/2022", situacion: "1", monto: "12000.00" },
            { periodo: "09/2022", situacion: "1", monto: "12000.00" },
            { periodo: "08/2022", situacion: "1", monto: "12000.00" },
            { periodo: "07/2022", situacion: "1", monto: "12000.00" },
            { periodo: "06/2022", situacion: "1", monto: "12000.00" },
            { periodo: "05/2022", situacion: "1", monto: "12000.00" },
            { periodo: "02/2022", situacion: "1", monto: "8000.00" },
            { periodo: "01/2022", situacion: "1", monto: "8000.00" },
            { periodo: "12/2021", situacion: "1", monto: "6000.00" },
            { periodo: "11/2021", situacion: "1", monto: "7000.00" },
          ],
        },
        {
          nombre: "TARJETA NARANJA S.A.",
          codigo_entidad: "70408",
          deudas: [
            { periodo: "04/2023", situacion: "1", monto: "19000.00" },
            { periodo: "03/2023", situacion: "1", monto: "16000.00" },
            { periodo: "02/2023", situacion: "1", monto: "7000.00" },
          ],
        },
      ],
      resumen_historico: {
        202111: {
          peor_situacion: "1",
          periodo: "11/2021",
          deuda_total: "7000.00",
          cantidad_entidades: 1,
        },
        202112: {
          peor_situacion: "1",
          periodo: "12/2021",
          deuda_total: "6000.00",
          cantidad_entidades: 1,
        },
        202201: {
          peor_situacion: "1",
          periodo: "01/2022",
          deuda_total: "8000.00",
          cantidad_entidades: 1,
        },
        202202: {
          peor_situacion: "1",
          periodo: "02/2022",
          deuda_total: "8000.00",
          cantidad_entidades: 1,
        },
        202205: {
          peor_situacion: "1",
          periodo: "05/2022",
          deuda_total: "12000.00",
          cantidad_entidades: 1,
        },
        202206: {
          peor_situacion: "1",
          periodo: "06/2022",
          deuda_total: "12000.00",
          cantidad_entidades: 1,
        },
        202207: {
          peor_situacion: "1",
          periodo: "07/2022",
          deuda_total: "12000.00",
          cantidad_entidades: 1,
        },
        202208: {
          peor_situacion: "1",
          periodo: "08/2022",
          deuda_total: "12000.00",
          cantidad_entidades: 1,
        },
        202209: {
          peor_situacion: "1",
          periodo: "09/2022",
          deuda_total: "12000.00",
          cantidad_entidades: 1,
        },
        202210: {
          peor_situacion: "1",
          periodo: "10/2022",
          deuda_total: "12000.00",
          cantidad_entidades: 1,
        },
        202211: {
          peor_situacion: "1",
          periodo: "11/2022",
          deuda_total: "12000.00",
          cantidad_entidades: 1,
        },
        202212: {
          peor_situacion: "1",
          periodo: "12/2022",
          deuda_total: "13000.00",
          cantidad_entidades: 1,
        },
        202301: {
          peor_situacion: "2",
          periodo: "01/2023",
          deuda_total: "17000.00",
          cantidad_entidades: 1,
        },
        202302: {
          peor_situacion: "1",
          periodo: "02/2023",
          deuda_total: "13000.00",
          cantidad_entidades: 2,
        },
        202303: {
          peor_situacion: "1",
          periodo: "03/2023",
          deuda_total: "28000.00",
          cantidad_entidades: 2,
        },
        202304: {
          peor_situacion: "1",
          periodo: "04/2023",
          deuda_total: "31000.00",
          cantidad_entidades: 2,
        },
      },
    },
    nivelSocioeconomico: {
      nse_personal: "C3",
      nse_rangos: { desde: "110429", hasta: "156528" },
    },
    domicilios: [
      {
        calle: "CAFAYATE 5000",
        altura: "",
        extra: "",
        barrio: "",
        localidad: "CIUDAD AUTONOMA DE BUENOS AIRES",
        provincia: "CIUDAD AUTONOMA DE BUENOS AIRES",
        cp: "",
        tipo: "PERSONAL",
        fecha: "2021-01-01",
      },
    ],
    operadoresGranos: false,
    cantidadEmpleados: false,
    celulares: false,
    empleador: {
      remuneracion: "133566.33",
      cuit: "30709492922",
      periodo: "202304",
      razon_social: "CAT TECHNOLOGIES ARGENTINA SOCIEDAD ANONIMA",
      primer_periodo: "202302",
      primer_periodo_historico: "202103",
      identidad: {
        cuit: "30709492922",
        numero_documento: "",
        tipo_documento: "",
        nombre_completo: "CAT TECHNOLOGIES ARGENTINA SOCIEDAD ANONIMA",
        sexo: "",
        fecha_nacimiento: "",
        clase: "",
        localidad: "CAPITAL FEDERAL",
        provincia: "CAPITAL FEDERAL CIUDAD AUTONOMA BUENOS AIRES",
        tipo_entidad: "J",
        fecha_inscripcion: "12/01/2006",
        fecha_fallecimiento: "",
        fallecido: "NO",
        cuit_baja: "NO",
        codigo_actividad: "822000",
        actividad: "SERVICIOS DE CALL CENTER",
        anios: "",
        anios_inscripcion: "17",
        jubilado: "NO",
        pensionado: "NO",
        localidad_array: ["CAPITAL FEDERAL", ""],
        provincia_array: ["CAPITAL FEDERAL", "CIUDAD AUTONOMA BUENOS AIRES"],
      },
      domicilios: [
        {
          calle: "PERON JUAN TTE.GRAL.",
          altura: "867",
          extra: "",
          barrio: "",
          localidad: "",
          provincia: "CIUDAD AUTONOMA BUENOS AIRES",
          cp: "1038",
          tipo: "FISCAL",
          fecha: "2023-05-16",
        },
        {
          calle: "PERON JUAN TTE.GRAL.",
          altura: "867",
          extra: "",
          barrio: "",
          localidad: "CAPITAL FEDERAL",
          provincia: "CAPITAL FEDERAL",
          cp: "1038",
          tipo: "FISCAL",
          fecha: "2014-06-01",
        },
      ],
      telefono: [
        {
          nombre: "CAT TECHNOLOGIES SA",
          telefono: "(011) 4132-2200",
          domicilio: "TGRAL J PERON 867 1",
          cp: "1038",
          localidad: "CIUDAD DE BUENOS AIRES",
          provincia: "BUENOS AIRES",
          guia: "2014",
        },
      ],
      mail: [{ mail: "EPRESAS@CAT-TECHNOLOGIES.COM" }],
      soaAfipA4Online: {
        sexo: "",
        clase: "",
        email: [
          {
            estado: "No Verificado",
            direccion: "epresas@cat-technologies.com",
            tipoEmail: "E-VENTANILLA",
          },
          {
            estado: "No Confirmado por Aplicacion",
            direccion: "contador@martinezrao.com",
            tipoEmail: "TRIBUTARIO",
          },
        ],
        nombre: "",
        regimen: {
          estado: "ACTIVO",
          periodo: 201111,
          idRegimen: 94,
          idImpuesto: 217,
          tipoRegimen: "RETENCION",
          descripcionRegimen:
            "REG.RET.A LAS GANANCIAS - LOCACIONES DE OBRAS Y/O SERVICIOS, NO EJECUTADOS EN RELACION DE DEPENDENCIA, QUE NO SE ENCUENTREN TAXATIVAMENTE MENCIONADOS EN LOS INCISOS I Y J.",
        },
        apellido: "",
        impuesto: [
          {
            estado: "ACTIVO",
            periodo: 200610,
            diaPeriodo: 1,
            idImpuesto: 301,
            ffInscripcion: "2006-09-29",
            descripcionImpuesto: "EMPLEADOR-APORTES SEG. SOCIAL",
            ffInscripcionFormato: "29/09/2006",
          },
          {
            estado: "ACTIVO",
            periodo: 201312,
            diaPeriodo: 1,
            idImpuesto: 25,
            ffInscripcion: "2014-03-27",
            descripcionImpuesto: "GANANCIA MINIMA PRESUNTA",
            ffInscripcionFormato: "27/03/2014",
          },
          {
            estado: "ACTIVO",
            periodo: 201111,
            diaPeriodo: 1,
            idImpuesto: 217,
            ffInscripcion: "2011-12-18",
            descripcionImpuesto: "SICORE-IMPTO.A LAS GANANCIAS",
            ffInscripcionFormato: "18/12/2011",
          },
          {
            estado: "ACTIVO",
            periodo: 200601,
            diaPeriodo: 12,
            idImpuesto: 10,
            ffInscripcion: "2006-01-12",
            descripcionImpuesto: "GANANCIAS SOCIEDADES",
            ffInscripcionFormato: "12/01/2006",
          },
          {
            estado: "ACTIVO",
            periodo: 200601,
            diaPeriodo: 12,
            idImpuesto: 30,
            ffInscripcion: "2006-01-12",
            descripcionImpuesto: "IVA",
            ffInscripcionFormato: "12/01/2006",
          },
          {
            estado: "ACTIVO",
            periodo: 200701,
            diaPeriodo: 1,
            idImpuesto: 103,
            ffInscripcion: "2009-08-10",
            descripcionImpuesto: "REGIMENES DE INFORMACI\u00d3N",
            ffInscripcionFormato: "10/08/2009",
          },
        ],
        relacion: [
          {
            nombre: "SERAFINI JAVIER GUSTAVO",
            idPersona: 30709492922,
            ffRelacion: "2017-05-09",
            tipoRelacion: "SOCIEDAD CON INTEGRANTES",
            ffVencimiento: "2019-05-09T12:00:00-03:00",
            subtipoRelacion: "PRESIDENTE",
            ffRelacionFormato: "09/05/2017",
            idPersonaAsociada: 20134114003,
          },
          {
            nombre: "PUSTERLA ALDO EMILIO",
            idPersona: 30709492922,
            ffRelacion: "2012-04-10",
            tipoRelacion: "SOCIEDAD CON INTEGRANTES",
            subtipoRelacion: "OTROS CARGOS",
            ffRelacionFormato: "10/04/2012",
            idPersonaAsociada: 20134325438,
          },
          {
            nombre: "GONZALEZ GUSTAVO MARTIN",
            idPersona: 30709492922,
            ffRelacion: "2017-05-09",
            tipoRelacion: "SOCIEDAD CON INTEGRANTES",
            ffVencimiento: "2019-05-09T12:00:00-03:00",
            subtipoRelacion: "DIRECTOR SUPLENTE",
            ffRelacionFormato: "09/05/2017",
            idPersonaAsociada: 20231208780,
          },
          {
            nombre: "MARTINEZ DIEGO MAXIMILIANO",
            idPersona: 30709492922,
            ffRelacion: "2017-11-30",
            tipoRelacion: "PODERDANTE",
            subtipoRelacion: "FORMULARIO 3283 PUNTOS 1 A 10",
            ffRelacionFormato: "30/11/2017",
            idPersonaAsociada: 20252491164,
          },
          {
            nombre: "BENITEZ ARRUA MIGUEL ANGEL",
            idPersona: 30709492922,
            ffRelacion: "2012-06-19",
            tipoRelacion: "PODERDANTE",
            subtipoRelacion: "F. 3283 REGISTRACI\u00d3N ANTERIOR AL 23/11/2012",
            ffRelacionFormato: "19/06/2012",
            idPersonaAsociada: 20942792515,
          },
        ],
        telefono: "",
        actividad: [
          {
            orden: 1,
            periodo: 201311,
            idActividad: 620900,
            nomenclador: 883,
            descripcionActividad: "SERVICIOS DE INFORM\u00c1TICA N.C.P.",
          },
          {
            orden: 2,
            periodo: 201312,
            idActividad: 822000,
            nomenclador: 883,
            descripcionActividad: "SERVICIOS DE CALL CENTER",
          },
        ],
        categoria: "",
        domicilio: [
          {
            codPostal: "1038",
            direccion: "PERON JUAN TTE.GRAL. 867",
            idProvincia: 0,
            tipoDomicilio: "FISCAL",
            descripcionProvincia: "CIUDAD AUTONOMA BUENOS AIRES",
          },
          {
            codPostal: "1038",
            direccion: "PERON JUAN TTE.GRAL. 867",
            idProvincia: 0,
            tipoDomicilio: "LEGAL/REAL",
            descripcionProvincia: "CIUDAD AUTONOMA BUENOS AIRES",
          },
        ],
        idPersona: 30709492922,
        mesCierre: 12,
        tipoClave: "CUIT",
        dependencia: "",
        estadoClave: "ACTIVO",
        razonSocial: "CAT TECHNOLOGIES ARGENTINA SOCIEDAD ANONIMA",
        sexoFormato: "",
        tipoPersona: "JURIDICA",
        fechaJubilado: "",
        formaJuridica: "SOC. ANONIMA",
        leyJubilacion: "",
        tipoDocumento: "",
        nombreCompleto:
          "CAT TECHNOLOGIES ARGENTINA SOCIEDAD ANONIMA SOC. ANONIMA",
        tipoResidencia: "",
        fechaNacimiento: "",
        numeroDocumento: "",
        fechaInscripcion: "2006-01-12",
        numeroInscripcion: 15841,
        fechaFallecimiento: "",
        fechaContratoSocial: "2005-12-09",
        organismoOriginante: "",
        fechaJubiladoFormato: "",
        localidadInscripcion: "",
        organismoInscripcion: "IGJ",
        provinciaInscripcion: "",
        claveInactivaAsociada: "",
        fechaNacimientoFormato: "",
        fechaInscripcionFormato: "12/01/2006",
        tipoOrganismoOriginante: "",
        cantidadSociosEmpresaMono: "",
        fechaFallecimientoFormato: "",
        fechaVencimientoMigracion: "",
        porcentajeCapitalNacional: 100,
        fechaContratoSocialFormato: "09/12/2005",
        fechaVencimientoMigracionFormato: "",
      },
      cantidadEmpleados: { cantidad: 2934, tamanio: "Grande" },
    },
    scoringLoteo: {
      detalle: "EXCELENTE",
      deuda: "10333.33",
      credito: "267132.66",
      scoring: 5,
      actividad: {
        empleado: "SI",
        monotributista: "NO",
        autonomo: "NO",
        empleador: "NO",
      },
      detalle_scoring: {
        bcraOnline: 5,
        sinActividad: 5,
        bcra12Meses: 6,
        bcra12a24Meses: 6,
        chequesRechazadosOnline: 6,
        chequesRechazados24meses: 6,
        ingresos: 6,
        legal: 6,
        edad: 6,
        fallecido: 6,
      },
    },
    domiciliosPersonasRelacionadas: [
      {
        datos_persona: {
          cuit: "20236019994",
          nombre_completo: "PALOPOLI ALBERTO JAVIER",
          clase: "1974",
          anios: "49",
        },
        domicilios: [
          {
            calle: "EVARISTO CARRIEGO 1267 MZA 7 CASA 24 MZA 7 CASA 24",
            altura: "",
            extra: "",
            barrio: "",
            localidad: "MORENO",
            provincia: "BUENOS AIRES",
            cp: "1744",
            tipo: "PERSONAL",
            fecha: "2021-01-01",
          },
          {
            calle: "LARRALDE",
            altura: "1083",
            extra: "",
            barrio: "",
            localidad: "MORENO",
            provincia: "BUENOS AIRES",
            cp: "1744",
            tipo: "FISCAL",
            fecha: "2022-04-18",
          },
        ],
      },
      {
        datos_persona: {
          cuit: "20238824274",
          nombre_completo: "DUARTE JORGE DANIEL",
          clase: "1974",
          anios: "49",
        },
        domicilios: [
          {
            calle: "CUZCO 1803",
            altura: "",
            extra: "",
            barrio: "",
            localidad: "WILLIAM C MORRIS",
            provincia: "BUENOS AIRES",
            cp: "",
            tipo: "PERSONAL",
            fecha: "2021-01-01",
          },
          {
            calle: "CALIFORNIA",
            altura: "3500",
            extra: "35",
            barrio: "",
            localidad: "",
            provincia: "CIUDAD AUTONOMA BUENOS AIRES",
            cp: "1437",
            tipo: "LEGAL",
            fecha: "2022-08-26",
          },
          {
            calle: "CALIFORNIA",
            altura: "3500",
            extra: "35",
            barrio: "",
            localidad: "CIUDAD AUTONOMA BUENOS AI",
            provincia: "CAP. FEDERA",
            cp: "1437",
            tipo: "PERSONAL",
            fecha: "2020-10-01",
          },
          {
            calle: "ALEM LEANDRO N. AV.",
            altura: "1050",
            extra: "9 ",
            barrio: "",
            localidad: "CAPITAL FEDERAL",
            provincia: "CAPITAL FEDERAL",
            cp: "1001",
            tipo: "LABORAL",
            fecha: "2014-06-01",
          },
        ],
      },
      {
        datos_persona: {
          cuit: "20288668117",
          nombre_completo: "FORQUEDA RODOLFO ESTEBAN",
          clase: "1981",
          anios: "42",
        },
        domicilios: [
          {
            calle: "COLON 795 DPTO/CASA:5",
            altura: "",
            extra: "",
            barrio: "",
            localidad: "LUJAN",
            provincia: "BUENOS AIRES",
            cp: "6700",
            tipo: "PERSONAL",
            fecha: "2021-01-01",
          },
          {
            calle: "COLON",
            altura: "795",
            extra: "5",
            barrio: "",
            localidad: "LUJAN",
            provincia: "BUENOS AIRES",
            cp: "6700",
            tipo: "FISCAL",
            fecha: "2020-08-01",
          },
          {
            calle: "COLON",
            altura: "795",
            extra: "025",
            barrio: "",
            localidad: "LUJAN",
            provincia: "BUENOS AIRE",
            cp: "6700",
            tipo: "PERSONAL",
            fecha: "2020-10-01",
          },
          {
            calle: "DE MAYO AV.",
            altura: "1333",
            extra: "06",
            barrio: "",
            localidad: "CAPITAL FEDERAL",
            provincia: "CAPITAL FEDERAL",
            cp: "1085",
            tipo: "LABORAL",
            fecha: "2014-06-01",
          },
        ],
      },
      {
        datos_persona: {
          cuit: "20365940267",
          nombre_completo: "PALOPOLI NAHUEL DARIO",
          clase: "1991",
          anios: "31",
        },
        domicilios: [
          {
            calle: "20-MARINO ALBERTO 1594 BARRIO PRIMAVERA BARRIO PRIMAVERA",
            altura: "",
            extra: "",
            barrio: "",
            localidad: "BERAZATEGUI",
            provincia: "BUENOS AIRES",
            cp: "1884",
            tipo: "PERSONAL",
            fecha: "2021-01-01",
          },
          {
            calle: "ALMAFUERTE",
            altura: "1150",
            extra: "",
            barrio: "",
            localidad: "FRANCISCO ALVAREZ",
            provincia: "BUENOS AIRE",
            cp: "1746",
            tipo: "PERSONAL",
            fecha: "2020-10-01",
          },
        ],
      },
      {
        datos_persona: {
          cuit: "20410052688",
          nombre_completo: "DUARTE JULIAN LUCAS DANIEL",
          clase: "1998",
          anios: "25",
        },
        domicilios: [
          {
            calle: "CALIFORNIA MZ7 3500",
            altura: "",
            extra: "",
            barrio: "",
            localidad: "CIUDAD AUTONOMA DE BUENOS AIRES",
            provincia: "CIUDAD AUTONOMA DE BUENOS AIRES",
            cp: "",
            tipo: "PERSONAL",
            fecha: "2019-01-01",
          },
        ],
      },
      {
        datos_persona: {
          cuit: "20458685089",
          nombre_completo: "PALOPOLI JAVIER LUCA VALENTIN",
          clase: "2004",
          anios: "19",
        },
        domicilios: [
          {
            calle: "115 1218",
            altura: "",
            extra: "",
            barrio: "",
            localidad: "BERAZATEGUI",
            provincia: "BUENOS AIRES",
            cp: "1884",
            tipo: "PERSONAL",
            fecha: "2021-01-01",
          },
          {
            calle: "COLON",
            altura: "795",
            extra: "5 00",
            barrio: "",
            localidad: "LUJAN",
            provincia: "BUENOS AIRES",
            cp: "6700",
            tipo: "LEGAL",
            fecha: "2021-01-06",
          },
        ],
      },
      {
        datos_persona: {
          cuit: "23408528259",
          nombre_completo: "GUZMAN NICOLAS ALEJANDRO",
          clase: "1997",
          anios: "25",
        },
        domicilios: [
          {
            calle: "CAFAYATE 5000",
            altura: "",
            extra: "",
            barrio: "",
            localidad: "CIUDAD AUTONOMA DE BUENOS AIRES",
            provincia: "CIUDAD AUTONOMA DE BUENOS AIRES",
            cp: "",
            tipo: "PERSONAL",
            fecha: "2021-01-01",
          },
          {
            calle: "CAFAYATE",
            altura: "5000",
            extra: "A 21",
            barrio: "",
            localidad: "",
            provincia: "CIUDAD AUTONOMA BUENOS AIRES",
            cp: "1439",
            tipo: "FISCAL",
            fecha: "2022-06-23",
          },
          {
            calle: "CAFAYATE",
            altura: "5000",
            extra: "21A",
            barrio: "",
            localidad: "CIUDAD AUTONOMA BUENOS AI",
            provincia: "CAP. FEDERA",
            cp: "1439",
            tipo: "PERSONAL",
            fecha: "2020-10-01",
          },
        ],
      },
      {
        datos_persona: {
          cuit: "27255309337",
          nombre_completo: "FLORIANI ALEJANDRA ETHEL",
          clase: "1976",
          anios: "46",
        },
        domicilios: [
          {
            calle: "COLON 795 DPTO/CASA:5",
            altura: "",
            extra: "",
            barrio: "",
            localidad: "LUJAN",
            provincia: "BUENOS AIRES",
            cp: "6700",
            tipo: "PERSONAL",
            fecha: "2021-01-01",
          },
          {
            calle: "ALFONSINA STORNI",
            altura: "127",
            extra: "",
            barrio: "",
            localidad: "MORENO",
            provincia: "BUENOS AIRES",
            cp: "1744",
            tipo: "FISCAL",
            fecha: "2023-04-22",
          },
        ],
      },
    ],
    inmuebles: false,
    pamiOnline: false,
    telefonosPersonasRelacionadas: {
      27255309337: {
        datos_persona: {
          cuit: "27255309337",
          nombre_completo: "FLORIANI ALEJANDRA ETHEL",
        },
        telefonos: [
          {
            nombre: "FLORIANI ALEJANDRA",
            telefono: "(02323) 42-6017",
            domicilio: "COL\u00c3\u00b3N\u00a0795",
            cp: "6700",
            localidad: "LUJAN",
            provincia: "BUENOS AIRES",
            guia: "2016",
          },
        ],
        declarados: [{ numero: "1127036192" }, { numero: "2323490950" }],
        celulares: [{ numero: "1164509486", orden: "5" }],
      },
      20236019994: {
        datos_persona: {
          cuit: "20236019994",
          nombre_completo: "PALOPOLI ALBERTO JAVIER",
        },
        telefonos: false,
        declarados: [{ numero: "1164777404" }],
        celulares: [
          { numero: "1131103655", orden: "2" },
          { numero: "1169781495", orden: "5" },
        ],
      },
      20238824274: {
        datos_persona: {
          cuit: "20238824274",
          nombre_completo: "DUARTE JORGE DANIEL",
        },
        telefonos: false,
        declarados: [{ numero: "1138579856" }],
        celulares: [{ numero: "1160330276", orden: "1" }],
      },
      20288668117: {
        datos_persona: {
          cuit: "20288668117",
          nombre_completo: "FORQUEDA RODOLFO ESTEBAN",
        },
        telefonos: false,
        declarados: [
          { numero: "1115470056" },
          { numero: "1115474363" },
          { numero: "1150995076" },
        ],
        celulares: [{ numero: "2235698952", orden: "5" }],
      },
      20365940267: {
        datos_persona: {
          cuit: "20365940267",
          nombre_completo: "PALOPOLI NAHUEL DARIO",
        },
        telefonos: false,
        declarados: false,
        celulares: [
          { numero: "1134341717", orden: "5" },
          { numero: "1134515455", orden: "5" },
        ],
      },
      20458685089: {
        datos_persona: {
          cuit: "20458685089",
          nombre_completo: "PALOPOLI JAVIER LUCA VALENTIN",
        },
        telefonos: false,
        declarados: [{ numero: "1127036192" }],
        celulares: [{ numero: "2644763427", orden: "2" }],
      },
      27445229348: {
        datos_persona: {
          cuit: "27445229348",
          nombre_completo: "PALOPOLI NATASHA MARISA",
        },
        telefonos: false,
        declarados: [{ numero: "2235505500" }, { numero: "2236183582" }],
        celulares: false,
      },
    },
    id_informe: 32141441,
    fecha_solicitud: "2023-06-29",
  },
  id_informe: 32141441,
  fecha: "2023-06-29",
};
