## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/ip/*"
  to = "https://ipinfo.io/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  #headers = {X-From = "Netlify"}
  #signed = "API_SIGNATURE_TOKEN"

  ## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/API/*"
  to = "https://cofatest.sbfintech.net/API/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  #headers = {X-From = "Netlify"}
  #signed = "API_SIGNATURE_TOKEN"


[[redirects]]
  from = "/back/*"
  #to = "https://cofapp-production.up.railway.app/:splat"
  to = "http://localhost:3001/:splat"
  force = true
  status = 200
  #headers = {X-From = "Netlify"}
  #signed = "API_SIGNATURE_TOKEN"

[functions]
  node_bundler = "esbuild"

