export const STEPS = {
  STEP_1_DNI: 1,
  STEP_2_IDENTIDAD: 2,
  STEP_3_CELULAR: 3,
  STEP_4_PRESTAMO: 4,
  STEP_5_CLAVE: 5,
  STEP_6_VALIDAR_CBU: 6,
  STEP_7_MOBBEX: 7,
  STEP_8_VALIDAR_EMAIL: 8,
  STEP_9_VERIFICAR_PREAPROBADO: 9,
  STEP_10_VALIDAR_IDENTIDAD: 10,
  STEP_11_CONFIRMAR_PREAPROBADO: 11,
  STEP_99_ERROR: 99,
};
